# Generated by Django 5.1.2 on 2024-11-23 18:09

import apoloniaBeach.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=3, validators=[apoloniaBeach.validators.AlphaNumericValidator()]),
        ),
    ]
