# Generated by Django 5.1.2 on 2024-11-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='apartment',
            field=models.ManyToManyField(blank=True, null=True, related_name='owner', to='houses.apartment'),
        ),
    ]
