# Generated by Django 5.1.2 on 2024-11-16 10:24

import apoloniaBeach.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[apoloniaBeach.validators.NumericValidator()]),
        ),
    ]
