# Generated by Django 5.1.2 on 2024-11-19 17:00

import apoloniaBeach.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Rules', 'Rules'), ('Protocol', 'Protocol'), ('Letters', 'Letters'), ('Offers', 'Offers'), ('Invitation', 'Invitation'), ('Reports', 'Reports'), ('Other', 'Other')], max_length=15)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('document_type', models.CharField(choices=[('Rules', 'Rules'), ('Protocol', 'Protocol'), ('Letters', 'Letters'), ('Offers', 'Offers'), ('Invitation', 'Invitation'), ('Reports', 'Reports'), ('Other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='documents/', validators=[apoloniaBeach.validators.file_validator])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
