# Generated by Django 5.1.2 on 2024-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_apartment_alter_album_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BGN', 'BGN')], max_length=3, null=True),
        ),
    ]
