# Generated by Django 5.1.2 on 2024-11-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BGN', 'BGN')], default='BGN', max_length=3),
        ),
    ]
