# Generated by Django 5.1.2 on 2024-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
