# Generated by Django 5.1.2 on 2024-11-26 15:36

import apoloniaBeach.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[apoloniaBeach.validators.file_validator], verbose_name='photo'),
        ),
    ]
